{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

<div id="profile-edit-hide-friends-wrapper">
	{{include file="field_yesno.tpl" field=$yesno}}
</div>
